repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.0
    hooks:
      - id: terraform_fmt

  - repo: local
    hooks:
      - id: go-test-app
        name: Run Go tests for app/
        entry: bash -c 'if git diff --cached --name-only | grep -q "^app/"; then cd app && go test ./...; fi'
        language: system
        pass_filenames: false
        stages: [pre-push]
