name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - terraform/**
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Get GH App Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.11.4

      - name: Initialize Terraform
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: terraform init

      - name: Validate Terraform
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: terraform validate

      - name: Plan Terraform
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: terraform plan

      - name: Apply Terraform
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
