name: Terraform Plan

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - terraform/**
  workflow_dispatch:

permissions:
  pull-requests: write
  id-token: write

jobs:
  terraform-plan:
    name: Terraform Plan and PR Comment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Get GH App Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_GITHUB_OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.11.4

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Terraform Plan and Save Output
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          echo '```' > plan_output.txt
          terraform plan -no-color >> plan_output.txt
          echo '```' >> plan_output.txt

      - name: Post Plan as PR Comment
        uses: marocchino/sticky-pull-request-comment@v2.9.2
        with:
          path: terraform/plan_output.txt
